### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2018/PInfo1#1]
Dear Ranters,

This is your repository. 
Please store all your developed code here, so we can verify your progress throughout the semester.
Feel free to use issues such as this one to communicate amongst each other, with me and with @mencattini .

Your VM Server will be `pinfo1` (IP: 129.194.69.128 ).
Your logins are not activated yet, I hope it will be done at the end of this week.

Next to the official assignment (work out a project proposal),
I ask you to do the following initial tasks:

* Each team member should comment on this post, to verify that you receive these notifications.
* Create a README file for this repo (add some text, list the team members, etc.)

Best of luck

PS: I received emails from two groups (Ranters and  Petr Binko & co). If you should run into members of the third group, please tell them to contact me asap

**Comment by GiovannaTheo** [comment]
Got it.

**Comment by elipu** [comment]
Noted!

**Comment by arthurdeschamps** [comment]
Ranters for life

**Comment by kilian-ruchti** [comment]
I'm also here !

**Comment by jeremie-martin** [comment]
blah blah blah

**Comment by MBeaussart** [comment]
TADA !
