### ISSUE TITLE
Presentation 1 - quick feedback

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2018/PInfo1#3]
Theo asked me to have a look at your presentation. 
Here are a few things that I am missing (in either what you're going to say or show)

High level notes:
 * first slides: good pitch! you convinced me -> now give me more details about system architecture, etc

Detailed:
 * technical architecture - be prepared to answer questions like this (some are more easily answered with diagrams :wink:)
   - technology stack (which database, which front end framework, ...) 
   - which component talks to whom?
   - how are you serving static files?
   - where does the user talk to?
   - what communication technologies are going to be used?
   - which database
   - what are your plans on scaling?
   - ...
 * road-map:
   - estimation of effort (how many hours are required, how did you get to that number?)
   - how are you managing the project? (Scrum, Kanban, RUP, Waterfall, XP, ... ?) 
   - less text (e.g. "Have  a first GUI ready, where one can register..." -> "initial GUI; login + registration")
 * storyboards:  
   - imo a bit too abstract - you can actually make them look like browsers and use things that are not just rectangles. Examples:
        * [link](http://www.kadinyazilimci.com/wp-content/uploads/2014/08/Twitter-Wireframe.png) [link](https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/facebook-wireframe.svg) [link](http://pagestatus.info/web-browser-wireframe/8-useful-free-psd-for-wireframes-kits-idevie-web-browser-wireframe/)
       * search for " *anyWebpageName* + wireframe" (e.g. twitter wireframe)
   - you need to show the main parts of your application with story boards. (i.e. a user walkthrough) If two SB are enough to show this -> great!

**Comment by GiovannaTheo** [comment]
Thanks for the feedback! That's quite what we needed.
